### ISSUE TITLE
Using the GeoJson data from msyql database rather than assets folder

### ISSUE THREAD

**Issue by ckayuza** [mapbox/store-locator-android#19]
Can any one provide assistance on the use of GeoJson data from msyql database rather than assets folder.

**Comment by langsmith** [comment]
Hey @ckayuza , thanks for your interest in the Store Locator Kit.

After looking online, it looks like you should use Retrofit to make MySQL GET calls. PHP also seems to be mentioned. Anyways, you'll eventually want to parse through the response to create a `FeatureCollection`, rather than creating a `FeatureCollection` by [getting the GeoJSON from the assets folder](https://github.com/mapbox/store-locator-android/blob/master/StoreLocator/app/src/main/java/com/mapbox/storelocator/activity/MapActivity.java#L281-L288).

Some links to get you started:

- https://stackoverflow.com/questions/15732853/how-to-connect-android-app-to-mysql-database
- https://stackoverflow.com/questions/26124087/how-to-connect-mysql-in-my-android-project
- https://www.simplifiedcoding.net/android-retrofit-tutorial-to-insert-into-mysql-database/
- https://stackoverflow.com/questions/43572056/retrofit-2-0-get-query-parameter-not-passed-to-phps-get
- http://www.androidbie.com/2017/01/retrofit-android-insert-data-to.html
- https://stackoverflow.com/questions/32243719/consuming-restful-api-developed-in-php-and-mysql-in-android-using-retrofit
