### ISSUE TITLE
New Location not able to get icon

### ISSUE THREAD

**Issue by DeveloperLifestylehearing** [mapbox/store-locator-android#34]
I am trying to add new location in json file, I have copied similar data from previous location just changed lat, long and Location number to 6.

It taking me to that location on map when I click on it but it is not showing me location icon for it

**Comment by langsmith** [comment]
Hey @DeveloperLifestylehearing , thanks for using this project.

Have you modified any of the code in the [MapActivity](https://github.com/mapbox/store-locator-android/blob/master/StoreLocator/app/src/main/java/com/mapbox/storelocator/activity/MapActivity.java)? Are you getting any error messages in the logcat if you search for `Mbgl` in the logcat?

**Comment by langsmith** [comment]
What does your `list_of_locations.geojson` file look like? Can you post it here?

**Comment by DeveloperLifestylehearing** [comment]
I have fixed the issue, Thanks for help.

I have one more question If I want to add search for location and tooltip marker on icon of locations is there any ready made library available for it?

**Comment by DeveloperLifestylehearing** [comment]
Basically I want to add search for city and that will come up will all stores marked on map for particular city.

**Comment by langsmith** [comment]
> I have fixed the issue, Thanks for help.

🎊👏👏

> Basically I want to add search for city and that will come up will all stores marked on map for particular city.

We've got [the Places Plugin for Android](https://docs.mapbox.com/android/plugins/overview/places/), but in this particular case, I would use [the Java SDK's wrapper around the Mapbox Geocoding API](https://docs.mapbox.com/android/java/overview/geocoder/). 

Geocoding wrapper example is at https://docs.mapbox.com/android/java/examples/geocoding/. The response will return a list of `CarmenFeature` objects. Each `CarmenFeature` will have a `Point` within it:

```java
CarmenFeature feature = results.get(0);
Point featurePointCoordinate = feature.center();
double latitude = featurePointCoordinate.latitude();
double longitude = featurePointCoordinate.longitude();
```

https://docs.mapbox.com/search-playground/ is also helpful for fine tuning the exact geocoding query . Sounds like you'll want to use proximity and POI. For example, here are Starbucks in SF

https://docs.mapbox.com/search-playground/#{"url":"Starbucks","index":"mapbox.places","approx":true,"staging":false,"onCountry":false,"onType":true,"onProximity":true,"onBBOX":true,"onLimit":false,"onLanguage":false,"countries":[],"proximity":"-122.4328575660237,37.75204912532452","typeToggle":{"country":false,"region":false,"district":false,"postcode":false,"locality":false,"place":false,"neighborhood":false,"address":false,"poi":true},"types":["poi"],"bbox":"","limit":"","autocomplete":false,"languages":[],"languageStrict":false,"onDebug":false,"selectedLayer":"","debugClick":{},"localsearch":false,"query":"starbucks"}

<img width="1079" alt="Screen Shot 2019-09-20 at 9 02 50 AM" src="https://user-images.githubusercontent.com/4394910/65341538-774a4480-db85-11e9-9ea4-4ddf2b4b91ac.png">



More info about Android search options: https://docs.mapbox.com/android/plugins/overview/places/#search-options

**Comment by DeveloperLifestylehearing** [comment]
Am I able to run this plugin without internet?

**Comment by langsmith** [comment]
Certain parts. You could inject certain presaved locations into it and then show them on an offline map when they're selected in the drop down UI. But searching for new locations won't work offline because the plugin wraps around the Java SDK Geocoding API wrapper.

You can experiment. https://docs.mapbox.com/android/plugins/examples/global-location-search/ can get you started.

**Comment by DeveloperLifestylehearing** [comment]
Is there anyway that I can turn off direction api call from store locator as I have different stores in different province and I really don't need direction for it

**Comment by langsmith** [comment]
> Is there anyway that I can turn off direction api call from store locator as I have different stores in different province and I really don't need direction for it

Yep, you'd delete [the `getInformationFromDirectionsApi()` method](https://github.com/mapbox/store-locator-android/blob/master/StoreLocator/app/src/main/java/com/mapbox/storelocator/activity/MapActivity.java#L423-L475) and its usage at https://github.com/mapbox/store-locator-android/blob/master/StoreLocator/app/src/main/java/com/mapbox/storelocator/activity/MapActivity.java#L204-L206 and https://github.com/mapbox/store-locator-android/blob/master/StoreLocator/app/src/main/java/com/mapbox/storelocator/activity/MapActivity.java#L316

Because you're not getting routes to draw lines anymore, you can also delete (drawNavigationPolylineRoute)[https://github.com/mapbox/store-locator-android/blob/master/StoreLocator/app/src/main/java/com/mapbox/storelocator/activity/MapActivity.java#L543-L550] and its usage at https://github.com/mapbox/store-locator-android/blob/master/StoreLocator/app/src/main/java/com/mapbox/storelocator/activity/MapActivity.java#L450-L452

I'm going to close this ticket because the original question has been solved and the topic has now changed. Feel free to open a new ticket if you have further questions 👍
